### 
GET http://localhost:3000/volcab

### create new volcab
POST http://localhost:3000/v1/volcab/create
Content-Type: application/json

{
    "eng":"Hi",
    "vnese": ["xin chào"],
    "example":["hello baby"]
}

###  update
PUT http://localhost:3000/v1/volcab/update/tung
Content-Type: application/json

{
    "_id": "64a762f803fb58251d69f846",
    "eng":"go",
    "vnese":["đi"]
}

### delete

DELETE http://localhost:3000/v1/volcab/delete
Content-Type: application/json

{
    "_id":"64a762f803fb58251d69f846"
}

### get all
GET http://localhost:3000/v1/volcab/get-random


